// ============================================================================
// DAX Measures — Maroclear Suspension Detection Dashboard
//
// How to use:
//   Power BI Desktop → Report view → New Measure (paste each block)
//   Organise measures into display folders as noted in the comments.
//   All measures are written to be filter-context aware (slicer-responsive).
// ============================================================================


// ============================================================================
// TABLE: DailyKPIs
// Folder: [KPI]
// ============================================================================

// Total number of trades in the selected period
Total Trades =
SUM ( DailyKPIs[Total Trades] )

// Total trades flagged as HIGH RISK by the model
Flagged Trades =
SUM ( DailyKPIs[Flagged Trades] )

// Model-predicted suspension rate (flagged / total)
Predicted Suspension Rate =
DIVIDE (
    [Flagged Trades],
    [Total Trades],
    0
)

// Actual confirmed suspensions (settles with FLAR/RFSL/SFSL/PLAR status)
Actual Suspensions =
SUM ( DailyKPIs[Actual Suspensions] )

// Actual suspension rate — only over settled trades (excludes OPEN)
Actual Suspension Rate =
DIVIDE (
    [Actual Suspensions],
    SUMX (
        DailyKPIs,
        // Denominator excludes days with no settled trades yet (NULL actual rate)
        IF ( NOT ISBLANK ( DailyKPIs[Actual Rate] ), DailyKPIs[Total Trades], 0 )
    ),
    0
)

// Distinct participants flagged on any day in the selected period
High Risk Participants =
SUMX (
    DailyKPIs,
    DailyKPIs[High Risk Participants]
)

// Average model risk score across selected period
Avg Risk Score =
AVERAGEX (
    DailyKPIs,
    DailyKPIs[Avg Risk Score]
)

// Model precision: of flagged trades, how many were actually suspended
// Requires HighRiskTrades table to be loaded
Model Precision =
DIVIDE (
    CALCULATE (
        COUNTROWS ( HighRiskTrades ),
        HighRiskTrades[Outcome] = "Confirmed Suspension"
    ),
    CALCULATE (
        COUNTROWS ( HighRiskTrades ),
        HighRiskTrades[Outcome] <> "Pending"
    ),
    BLANK ()
)

// Model recall: of all actual suspensions, how many did the model catch
// Note: requires actual_suspensions from DailyKPIs as denominator
Model Recall =
DIVIDE (
    CALCULATE (
        COUNTROWS ( HighRiskTrades ),
        HighRiskTrades[Outcome] = "Confirmed Suspension"
    ),
    [Actual Suspensions],
    BLANK ()
)

// Change in predicted suspension rate vs prior period (for KPI card delta)
Predicted Rate vs Prior Period =
VAR CurrentRate = [Predicted Suspension Rate]
VAR PriorRate =
    CALCULATE (
        [Predicted Suspension Rate],
        DATEADD ( DimDate[Date], -1, MONTH )
    )
RETURN
    IF (
        NOT ISBLANK ( PriorRate ),
        CurrentRate - PriorRate,
        BLANK ()
    )


// ============================================================================
// TABLE: ParticipantSummary
// Folder: [Participant]
// ============================================================================

// Total trades for the selected participant(s) and date range
Participant Total Trades =
SUM ( ParticipantSummary[Total Trades] )

// Flagged trades for selected participant(s)
Participant Flagged Trades =
SUM ( ParticipantSummary[Flagged Trades] )

// Predicted suspension rate for selected participant
Participant Predicted Rate =
DIVIDE (
    [Participant Flagged Trades],
    [Participant Total Trades],
    0
)

// Actual suspension rate for selected participant
Participant Actual Rate =
DIVIDE (
    SUM ( ParticipantSummary[Actual Suspensions] ),
    SUMX (
        ParticipantSummary,
        IF (
            NOT ISBLANK ( ParticipantSummary[Suspension Rate] ),
            ParticipantSummary[Total Trades],
            0
        )
    ),
    0
)

// Average risk score for selected participant
Participant Avg Risk Score =
AVERAGEX (
    ParticipantSummary,
    ParticipantSummary[Avg Risk Score]
)

// Rank participants by predicted suspension rate (for league table sort)
Participant Risk Rank =
IF (
    HASONEVALUE ( ParticipantSummary[Participant] ),
    RANKX (
        ALL ( ParticipantSummary[Participant] ),
        CALCULATE ( [Participant Predicted Rate] ),
        ,
        DESC,
        DENSE
    )
)

// Top N participants by risk — use with TOPN visual filter
Top 10 Participants Flag =
IF ( [Participant Risk Rank] <= 10, 1, 0 )


// ============================================================================
// TABLE: SecurityHeatmap
// Folder: [Security]
// ============================================================================

// Total flagged trades for the selected ISIN(s)
Security Flagged Trades =
SUM ( SecurityHeatmap[Flagged Trades] )

// Average risk score across selected ISINs
Security Avg Risk Score =
AVERAGEX (
    SecurityHeatmap,
    SecurityHeatmap[Avg Risk Score]
)

// Actual suspension rate for selected ISIN(s)
Security Actual Rate =
DIVIDE (
    SUM ( SecurityHeatmap[Actual Suspensions] ),
    SUM ( SecurityHeatmap[Total Trades] ),
    0
)

// Average 5-day liquidity for selected ISIN
Security Avg Liquidity =
AVERAGEX (
    SecurityHeatmap,
    SecurityHeatmap[Avg Liquidity 5D]
)

// Average RSI for selected ISIN
Security Avg RSI =
AVERAGEX (
    SecurityHeatmap,
    SecurityHeatmap[Avg RSI 5]
)

// Rank ISINs by flagged trade count (for heatmap sort)
Security Risk Rank =
IF (
    HASONEVALUE ( SecurityHeatmap[ISIN] ),
    RANKX (
        ALL ( SecurityHeatmap[ISIN] ),
        CALCULATE ( [Security Flagged Trades] ),
        ,
        DESC,
        DENSE
    )
)


// ============================================================================
// TABLE: HighRiskTrades
// Folder: [Drill-through]
// ============================================================================

// Count of high-risk transactions in the drill-through view
Flagged Transaction Count =
COUNTROWS ( HighRiskTrades )

// Average suspension probability in the current filter context
Avg Suspension Probability =
AVERAGEX (
    HighRiskTrades,
    HighRiskTrades[suspension_probability]
)

// Percentage of drill-through rows that were confirmed suspensions
Confirmed Suspension % =
DIVIDE (
    CALCULATE (
        COUNTROWS ( HighRiskTrades ),
        HighRiskTrades[Outcome] = "Confirmed Suspension"
    ),
    COUNTROWS ( HighRiskTrades ),
    0
)

// Count of trades submitted after the 15:00 cutoff
Cutoff Breaches =
CALCULATE (
    COUNTROWS ( HighRiskTrades ),
    HighRiskTrades[cutoff_depasse] = 1
)

// Average buyer historical suspension rate in current context
Avg Buyer Historical Risk =
AVERAGEX (
    HighRiskTrades,
    HighRiskTrades[buyer_historical_suspens]
)

// Average seller historical suspension rate in current context
Avg Seller Historical Risk =
AVERAGEX (
    HighRiskTrades,
    HighRiskTrades[vendeur_historique_suspens]
)

// Risk score formatted as percentage string for card visual
Risk Score Label =
FORMAT ( [Avg Suspension Probability], "0.0%" )

// Dynamic title for drill-through page showing the filtered participant
Drill-through Title =
IF (
    ISFILTERED ( HighRiskTrades[trader_id] ),
    "High-Risk Trades — " & SELECTEDVALUE ( HighRiskTrades[trader_id], "Multiple Participants" ),
    "High-Risk Trades — All Participants"
)


// ============================================================================
// SHARED / CROSS-TABLE
// Folder: [Navigation]
// ============================================================================

// Last refresh timestamp for the data freshness indicator
Last Refreshed =
FORMAT (
    MAXX ( DailyKPIs, DailyKPIs[Refreshed At] ),
    "DD MMM YYYY HH:MM"
)

// Date range label for page header subtitle
Selected Date Range =
VAR MinDate = MIN ( DimDate[Date] )
VAR MaxDate = MAX ( DimDate[Date] )
RETURN
    FORMAT ( MinDate, "DD MMM YYYY" ) & "  →  " & FORMAT ( MaxDate, "DD MMM YYYY" )
